/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/redcar.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Redcar = (props)=>{
  const { nodes, materials } = useGLTF('./models/redcar.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.41, 0.01]} scale={7.36}>
        <group scale={0.01}>
          <mesh geometry={nodes.forMayaAOpolySurface29_forMayaAOblinn7_0.geometry} material={materials.forMayaAOblinn7} />
          <mesh geometry={nodes.forMayaAOpolySurface29_forMayaAOblinn6_0.geometry} material={materials.forMayaAOblinn6} />
        </group>
        <group scale={0.01}>
          <mesh geometry={nodes.forMayaAOpolySurface200_forMayaAOGrill2_0.geometry} material={materials.forMayaAOGrill2} />
          <mesh geometry={nodes.forMayaAOpolySurface200_Chrome_0.geometry} material={materials.Chrome} />
        </group>
        <group scale={0.01}>
          <mesh geometry={nodes.forMayaAOpSphere3_forMayaAOblinn10_0.geometry} material={materials.forMayaAOblinn10} />
          <mesh geometry={nodes.forMayaAOpSphere3_forMayaAOblinn6_0.geometry} material={materials.forMayaAOblinn6} />
        </group>
        <group scale={0.01}>
          <mesh geometry={nodes.forMayaAOpolySurface316_forMayaAOphong5_0.geometry} material={materials.forMayaAOphong5} />
          <mesh geometry={nodes.forMayaAOpolySurface316_Chrome_0.geometry} material={materials.Chrome} />
        </group>
        <group scale={0.01}>
          <mesh geometry={nodes.forMayaAOtruba_forMayaAOmi_car_paint_phen2_0.geometry} material={materials.forMayaAOmi_car_paint_phen2} />
          <mesh geometry={nodes.forMayaAOtruba_Chrome_0.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.forMayaAOtruba_forMayaAOlambert15_0.geometry} material={materials.forMayaAOlambert15} />
        </group>
        <group scale={0.01}>
          <mesh geometry={nodes.polySurface319_forMayaAOphong5_0.geometry} material={materials.forMayaAOphong5} />
          <mesh geometry={nodes.polySurface319_Chrome_0.geometry} material={materials.Chrome} />
        </group>
        <group scale={0.01}>
          <mesh geometry={nodes.forMayaAOpolySurface322_forMayaAOlambert16_0.geometry} material={materials.forMayaAOlambert16} />
          <mesh geometry={nodes.forMayaAOpolySurface322_forMayaAOlambert17_0.geometry} material={materials.forMayaAOlambert17} />
        </group>
        <mesh geometry={nodes.polySurface320_forMayaAOlambert16_0.geometry} material={materials.forMayaAOlambert16} scale={0.01} />
        <group scale={0.01}>
          <mesh geometry={nodes.forMayaAOpolySurface327_Chrome_0.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.forMayaAOpolySurface327_forMayaAOlambert17_0.geometry} material={materials.forMayaAOlambert17} />
        </group>
        <group scale={0.01}>
          <mesh geometry={nodes.polySurface322_forMayaAOblinn6_0.geometry} material={materials.forMayaAOblinn6} />
          <mesh geometry={nodes.polySurface322_forMayaAOblinn9_0.geometry} material={materials.forMayaAOblinn9} />
        </group>
        <group scale={0.01}>
          <mesh geometry={nodes.polySurface5_forMayaAOblinn7_0.geometry} material={materials.forMayaAOblinn7} />
          <mesh geometry={nodes.polySurface5_forMayaAOblinn6_0.geometry} material={materials.forMayaAOblinn6} />
          <mesh geometry={nodes.polySurface5_Chrome_0.geometry} material={materials.Chrome} />
          <mesh geometry={nodes.polySurface5_forMayaAOlambert16_0.geometry} material={materials.forMayaAOlambert16} />
          <mesh geometry={nodes.polySurface5_forMayaAOblinn9_0.geometry} material={materials.forMayaAOblinn9} />
        </group>
        <group position={[-0.04, 0.09, 0.12]} rotation={[Math.PI / 2, 0, 0]} scale={0}>
          <mesh geometry={nodes.pTorus1_Chrome_2_0.geometry} material={materials.Chrome_2} position={[-1, 0, 11]} scale={[0.67, 1, 0.67]} />
          <mesh geometry={nodes.pCube1_lamp1_0.geometry} material={materials.lamp1} position={[-1, 0.67, 11]} scale={[1.01, 0.9, 0.9]} />
          <mesh geometry={nodes.pTorus2_Chrome_2_0.geometry} material={materials.Chrome_2} position={[27.08, 0, 11]} scale={[0.67, 1, 0.67]} />
          <mesh geometry={nodes.pCube2_lamp1_0.geometry} material={materials.lamp1} position={[27.08, 0.67, 11]} scale={[1.01, 0.9, 0.9]} />
        </group>
        <group scale={0.01}>
          <mesh geometry={nodes.polySurface326_VRayMtl1_0.geometry} material={materials.VRayMtl1} />
          <mesh geometry={nodes.polySurface327_VRayMtl1_0.geometry} material={materials.VRayMtl1} />
        </group>
        <group position={[0, 0.05, -0.05]} rotation={[-0.26, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.polySurface347_Chrome_2_0.geometry} material={materials.Chrome_2} />
          <mesh geometry={nodes.polySurface347_logo222_0.geometry} material={materials.logo222} />
        </group>
        <group position={[-0.03, 0.08, -0.03]} rotation={[-0.08, -0.27, -0.02]} scale={0}>
          <mesh geometry={nodes.pCube4_miror_0.geometry} material={materials.miror} />
          <mesh geometry={nodes.pCube4_Chrome_2_0.geometry} material={materials.Chrome_2} />
        </group>
        <group position={[-0.31, 0.12, -0.03]} rotation={[Math.PI / 2, -0.2, 0.27]} scale={0.01}>
          <group position={[30.67, 0.51, -0.62]} rotation={[0.46, 0.25, 0]} scale={0.16}>
            <mesh geometry={nodes.polySurface351_chromedvorn_0.geometry} material={materials.chromedvorn} />
            <mesh geometry={nodes.polySurface352_chromedvorn_0.geometry} material={materials.chromedvorn} />
            <mesh geometry={nodes.polySurface353_chromedvorn_0.geometry} material={materials.chromedvorn} />
            <mesh geometry={nodes.polySurface354_rezinDvorn_0.geometry} material={materials.rezinDvorn} />
            <mesh geometry={nodes.polySurface355_chromedvorn_0.geometry} material={materials.chromedvorn} />
          </group>
          <group position={[0.33, 5.83, -0.37]} rotation={[0.09, -0.02, -0.15]}>
            <group position={[0.14, 0, 1.9]} rotation={[0, 0.05, 0]}>
              <mesh geometry={nodes.pCylinder1_Chrome_2_0.geometry} material={materials.Chrome_2} position={[40.24, 0.53, -2.19]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.94} />
              <mesh geometry={nodes.pCylinder2_chromedvorn_0.geometry} material={materials.chromedvorn} position={[40.84, 0.53, -1.95]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.41, 0.5, 0.41]} />
              <mesh geometry={nodes.pCylinder3_rezinDvorn_0.geometry} material={materials.rezinDvorn} position={[40.84, 0.53, -1.93]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.46, 0.56, 0.46]} />
            </group>
            <mesh geometry={nodes.polySurface349_Chrome_2_0.geometry} material={materials.Chrome_2} position={[36.37, 2.64, -3.8]} rotation={[0, 0, -Math.PI / 2]} scale={[0.08, 0.11, 0.11]} />
            <mesh geometry={nodes.pCylinder4_chromedvorn_0.geometry} material={materials.chromedvorn} position={[38.29, 0.53, -2.19]} rotation={[0, 0, -Math.PI / 2]} scale={[0.41, 5.55, 0.41]} />
          </group>
        </group>
        <mesh geometry={nodes.forMayaAOpolySurface45_forMayaAOmi_car_paint_phen2_0.geometry} material={materials.forMayaAOmi_car_paint_phen2} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface317_forMayaAOmi_car_paint_phen2_0.geometry} material={materials.forMayaAOmi_car_paint_phen2} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface318_forMayaAOmi_car_paint_phen2_0.geometry} material={materials.forMayaAOmi_car_paint_phen2} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface274_forMayaAOmi_car_paint_phen2_0.geometry} material={materials.forMayaAOmi_car_paint_phen2} scale={0.01} />
        <mesh geometry={nodes.forMayaAOReshotka_Chrome_0.geometry} material={materials.Chrome} scale={0.01} />
        <mesh geometry={nodes.forMayaAOznachok_forMayaAOAlpha_0.geometry} material={materials.forMayaAOAlpha} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface133_forMayaAOblinn6_0.geometry} material={materials.forMayaAOblinn6} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface197_forMayaAOphong5_0.geometry} material={materials.forMayaAOphong5} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpPipe6_Chrome_0.geometry} material={materials.Chrome} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCube4_forMayaAOlambert16_0.geometry} material={materials.forMayaAOlambert16} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCube1_forMayaAOlambert15_0.geometry} material={materials.forMayaAOlambert15} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface148_forMayaAOblinn11_0.geometry} material={materials.forMayaAOblinn11} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface149_forMayaAOblinn11_0.geometry} material={materials.forMayaAOblinn11} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface150_forMayaAOblinn11_0.geometry} material={materials.forMayaAOblinn11} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface151_forMayaAOblinn11_0.geometry} material={materials.forMayaAOblinn11} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface168_forMayaAOlambert15_0.geometry} material={materials.forMayaAOlambert15} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface166_forMayaAOmi_car_paint_phen2_0.geometry} material={materials.forMayaAOmi_car_paint_phen2} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface171_forMayaAOlambert15_0.geometry} material={materials.forMayaAOlambert15} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface181_forMayaAOphong5_0.geometry} material={materials.forMayaAOphong5} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface191_forMayaAOmi_car_paint_phen2_0.geometry} material={materials.forMayaAOmi_car_paint_phen2} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCylinder7_forMayaAOphong5_0.geometry} material={materials.forMayaAOphong5} scale={0.01} />
        <mesh geometry={nodes.forMayaAOnomer_forMayaAOnumber_0.geometry} material={materials.forMayaAOnumber} scale={0.01} />
        <mesh geometry={nodes.forMayaAOznachok1_logo222_0.geometry} material={materials.logo222} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCube5_forMayaAOlambert16_0.geometry} material={materials.forMayaAOlambert16} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCube6_forMayaAOlambert15_0.geometry} material={materials.forMayaAOlambert15} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCylinder1_forMayaAOlambert13_0.geometry} material={materials.forMayaAOlambert13} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpPipe5_Chrome_0.geometry} material={materials.Chrome} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCube9_forMayaAOlambert16_0.geometry} material={materials.forMayaAOlambert16} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCylinder8_forMayaAOlambert13_0.geometry} material={materials.forMayaAOlambert13} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface292_Chrome_0.geometry} material={materials.Chrome} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface83_Chrome_2_0.geometry} material={materials.Chrome_2} scale={0.01} />
        <mesh geometry={nodes.forMayaAOfaraz2_forMayaAOfrontLights_0.geometry} material={materials.forMayaAOfrontLights} scale={0.01} />
        <mesh geometry={nodes.forMayaAOfaraz1_forMayaAOrear_lights_0.geometry} material={materials.forMayaAOrear_lights} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface309_forMayaAOblinn6_0.geometry} material={materials.forMayaAOblinn6} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface295_Chrome_0.geometry} material={materials.Chrome} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface297_forMayaAOmi_car_paint_phen2_0.geometry} material={materials.forMayaAOmi_car_paint_phen2} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCylinder10_Chrome_0.geometry} material={materials.Chrome} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpSphere2_forMayaAOfrontLights_0.geometry} material={materials.forMayaAOfrontLights} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpTorus1_Chrome_0.geometry} material={materials.Chrome} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface310_forMayaAOlambert15_0.geometry} material={materials.forMayaAOlambert15} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCube12_forMayaAOlambert15_0.geometry} material={materials.forMayaAOlambert15} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCube15_forMayaAOlambert15_0.geometry} material={materials.forMayaAOlambert15} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCube11_forMayaAOlambert15_0.geometry} material={materials.forMayaAOlambert15} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCube13_forMayaAOlambert15_0.geometry} material={materials.forMayaAOlambert15} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpSphere7_Chrome_0.geometry} material={materials.Chrome} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface266_forMayaAOblinn9_0.geometry} material={materials.forMayaAOblinn9} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface221_Chrome_0.geometry} material={materials.Chrome} scale={0.01} />
        <mesh geometry={nodes.polySurface318_mafina2hdrilambert9_0.geometry} material={materials.mafina2hdrilambert9} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface320_forMayaAOphong2_0.geometry} material={materials.forMayaAOphong2} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface324_Chrome_0.geometry} material={materials.Chrome} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpolySurface326_forMayaAOlambert16_0.geometry} material={materials.forMayaAOlambert16} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCylinder11_forMayaAOblinn6_0.geometry} material={materials.forMayaAOblinn6} scale={0.01} />
        <mesh geometry={nodes.forMayaAOpCylinder12_forMayaAOlambert15_0.geometry} material={materials.forMayaAOlambert15} scale={0.01} />
        <mesh geometry={nodes.pSphere2_forMayaAOphong5_0.geometry} material={materials.forMayaAOphong5} position={[0.02, 0.08, 0.03]} rotation={[1.78, 1.55, Math.PI]} scale={0} />
        <mesh geometry={nodes.pSphere3_forMayaAOphong5_0.geometry} material={materials.forMayaAOphong5} position={[0.02, 0.08, 0.03]} rotation={[1.78, 1.55, Math.PI]} scale={0} />
        <mesh geometry={nodes.pSphere4_forMayaAOphong5_0.geometry} material={materials.forMayaAOphong5} position={[0.03, 0.07, 0.03]} rotation={[1.78, 0.56, Math.PI]} scale={0} />
        <mesh geometry={nodes.pSphere5_forMayaAOphong5_0.geometry} material={materials.forMayaAOphong5} position={[0.03, 0.06, 0.02]} rotation={[1.78, -0.48, Math.PI]} scale={0} />
        <mesh geometry={nodes.pSphere6_forMayaAOphong5_0.geometry} material={materials.forMayaAOphong5} position={[0.04, 0.07, 0.03]} rotation={[1.78, 0.49, Math.PI]} scale={0} />
        <mesh geometry={nodes.pSphere7_forMayaAOphong5_0.geometry} material={materials.forMayaAOphong5} position={[0.04, 0.06, 0.02]} rotation={[1.78, -0.53, Math.PI]} scale={0} />
      </group>
    </group>
  )
}


export default Redcar

useGLTF.preload('./models/redcar.glb')
